### ISSUE TITLE
Building with babel is crashing because of 'return' outside of function.

### ISSUE THREAD

**Issue by prvnbist** [ljharb/has-symbols#1]
I'm using babel to build my code but it's crashing with an error -

     SyntaxError: node_modules/has-symbols/test/shams/core-js.js: 'return' outside of function (11:1)

       9 | 		t.end();
      10 | 	});
    > 11 | 	return;
       | 	^
      12 | }
      13 | 
      14 | var hasSymbols = require('../../shams');

Any way I can resolve this?

**Comment by ljharb** [comment]
There’s a couple problems here - one, you’re running babel on code in node_modules, never do that; two, you’re running it on this package’s test code, which implies you’re not just running babel on third party code you’re using, but on the entire directory; three, top-level return works just fine in commonJS modules in node.

**Comment by PrasunKumarBiswas** [comment]
I am getting the same problem. have you been able to solve it?

**Comment by ljharb** [comment]
@PrasunKumarBiswas the solution is to avoid running babel on code in node_modules, and i believe there's also a babel config that allows a top level return.

**Comment by PrasunKumarBiswas** [comment]
I see, can you tell how to use the babel config to allow top level return?
I have been doing a separate project and ran into trouble when using babel in my build script.
![Capture3](https://user-images.githubusercontent.com/101058602/206544584-46017d08-0427-43e0-b064-e3f6c5af06d8.PNG)

**Comment by PrasunKumarBiswas** [comment]
this was my error in my code 
![Capture1](https://user-images.githubusercontent.com/101058602/206544803-6ad3e559-df91-4a99-8539-c0d9819310d5.PNG)

**Comment by ljharb** [comment]
Somehow you're transpiling not just node_modules code, but *test code*. I think you need to configure babel to ignore `node_modules/**`.
